### ISSUE TITLE
Suggestion - Update example to use the new apollo client components

### ISSUE THREAD

**Issue by dihmeetree** [dabit3/nextjs-with-aws-appsync#1]
Just a suggestion.. but updating the example to use the new apollo client components would be great! Check here for more info and examples! https://www.apollographql.com/docs/react/essentials/queries.html

Here's an example to do a simple query!
```
import gql from "graphql-tag";
import { Query } from "react-apollo";

const GET_DOGS = gql`
  {
    dogs {
      id
      breed
    }
  }
`;

const Dogs = ({ onDogSelected }) => (
  <Query query={GET_DOGS}>
    {({ loading, error, data }) => {
      if (loading) return "Loading...";
      if (error) return `Error! ${error.message}`;

      return (
        <select name="dog" onChange={onDogSelected}>
          {data.dogs.map(dog => (
            <option key={dog.id} value={dog.breed}>
              {dog.breed}
            </option>
          ))}
        </select>
      );
    }}
  </Query>
);
```

**Note**: It's so much easier to use/read/etc :D Let me know if you don't have the time to do this and I can probably submit a PR with the changes to use the new components :)

**Comment by Enalmada** [comment]
Yes, I am very curious about nextjs with appsync and as a new user I believe using the new components would increase the chances new users will adopt app sync significantly.
