### ISSUE TITLE
Sample does not run - apollo-link\lib\linkUtils.js incorrectly imported

### ISSUE THREAD

**Issue by yoDon** [dabit3/nextjs-with-aws-appsync#3]
nextjs-with-aws-appsync does not run. It appears to be importing apollo dependencies incorrectly, leading to un-webpacked es6 files being loaded directly. This manifests as an apollo-link related error,
as shown below:

```
D:\...\node_modules\apollo-link\lib\linkUtils.js:25
import { getOperationName } from 'apollo-utilities';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by yoDon** [comment]
**Update** 
this appears to be an issue with the 1.3.4 release of aws-appsync and 1.1.3 release of aws-appsync-react. For background see See https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/233

**Workaround**
I needed to remove next-apollo-appsync from my package.json and package-lock.json and then do an npm install to flush the old next-apollo-appsync (which had cached a bad requires for the 1.3.3 and 1.1.3 releases).

Then I edited my package.json to roll back to 
```
    "aws-appsync": "1.3.3",
    "aws-appsync-react": "1.1.3",
```
and did another npm install.

Finally I npm install --save next-apollo-appsync which restored next-apollo-appsync and respected the previously installed 1.3.3 and 1.1.3 packages.

**Comment by mayur-padshala** [comment]
@yoDon I was able to resolve this on latest version. The latest version does not seem to be compiled properly.
[Checkout the answer here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/233#issuecomment-427003063) on the issue awslabs/aws-mobile-appsync-sdk-js#233

**Comment by yoDon** [comment]
I'm going to close this issue based on the update by @mayur-novus
